import test from 'node:test';
import assert from 'node:assert/strict';
import {ordinal} from '../web/dates.mjs';
import {viewRange,moveAnchor,overlaps,eventTime,appointments,shiftDetails} from '../web/planner-model.mjs';
import {readPlannerPreferences} from '../web/planner-renderer.mjs';
import {defaults} from '../web/config.mjs';
const day=ordinal('2026-09-06');
const event=(overrides={})=>({key:'test',calendar:1,title:'Busy',startDay:day,endDay:day+1,startSecond:20*3600,endSecond:8*3600,kind:2,allDay:false,sortTime:day*86400000,...overrides});
test('Sunday rolling range begins on Sunday, not the preceding Monday',()=>assert.deepEqual(viewRange(day,'rolling'),{first:day,count:7}));
test('calendar week honours Monday or Sunday first',()=>{assert.equal(viewRange(day,'week',1).first,day-6);assert.equal(viewRange(day,'week',0).first,day);});
test('rolling range crosses month and year without padding',()=>{for(const d of ['2026-09-29','2026-12-29'])assert.deepEqual(viewRange(ordinal(d),'rolling'),{first:ordinal(d),count:7});});
test('month handles four, five and six rows',()=>{assert.equal(viewRange(ordinal('2021-02-08'),'month',1).count,28);assert.equal(viewRange(day,'month',1).count,35);assert.equal(viewRange(ordinal('2026-03-15'),'month',1).count,42);});
test('navigation moves seven civil days or clamps a month end',()=>{assert.equal(moveAnchor(day,false,1),day+7);assert.equal(moveAnchor(ordinal('2026-01-31'),true,1),ordinal('2026-02-28'));});
test('overnight shift appears on both days, with honest continuation label',()=>{assert.ok(overlaps(event(),day));assert.ok(overlaps(event(),day+1));assert.equal(eventTime(event(),day),'20:00–08:00 (+1 day)');assert.equal(eventTime(event(),day+1),'Until 08:00');});
test('exclusive midnight end does not occupy following day',()=>{assert.equal(overlaps(event({endSecond:0}),day+1),false);assert.equal(overlaps(event({allDay:true}),day+1),false);});
test('zero-duration event belongs to its start date',()=>{const e=event({endDay:day,endSecond:20*3600});assert.equal(overlaps(e,day),true);assert.equal(overlaps(e,day+1),false);});
test('private rota title stays masked; shift details use status and time only',()=>{const rows=shiftDetails([event()],defaults(),day);assert.deepEqual(rows,['On call · 20:00–08:00 (+1 day)']);});
test('work and call times remain separate',()=>{const rows=shiftDetails([event(),event({kind:1,startSecond:8*3600,endDay:day,endSecond:17*3600})],defaults(),day);assert.equal(rows.length,2);assert.match(rows[0],/^On call/);assert.match(rows[1],/^Work/);});
test('rota markers are not duplicated as ordinary appointments',()=>assert.equal(appointments([event()],defaults()).length,0));
test('dedup matches earliest configured calendar, not input order',()=>{const c={...defaults(),deduplicate:true};const a=event({kind:0,calendar:3}),b=event({kind:0,calendar:0});assert.deepEqual(appointments([a,b],c),[b]);assert.equal(appointments([a,b],{...c,deduplicate:false}).length,2);});
test('preferences tolerate unavailable/corrupt storage and unsupported mode',()=>{assert.equal(readPlannerPreferences({getItem(){throw Error();}}).school,true);assert.equal(readPlannerPreferences({getItem:()=>'{broken'}).view,null);assert.equal(readPlannerPreferences({getItem:()=>'{"view":"bad"}'}).view,null);});
